[build]
builder = "NIXPACKS"

[deploy]
numReplicas = 1
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
httpPath = "/"
initialDelaySeconds = 60
periodSeconds = 10 